tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface": "#f7f9fb",
                "secondary": "#515f74",
                "surface-container-lowest": "#ffffff",
                "primary": "#183ce6",
                "on-tertiary-fixed": "#370e00",
                "on-tertiary": "#ffffff",
                "outline": "#757688",
                "on-secondary-fixed-variant": "#3a485b",
                "on-primary-fixed": "#000f5d",
                "surface-variant": "#e0e3e5",
                "outline-variant": "#c5c5d9",
                "inverse-primary": "#bbc3ff",
                "error-container": "#ffdad6",
                "error": "#ba1a1a",
                "surface-bright": "#f7f9fb",
                "secondary-fixed": "#d5e3fc",
                "on-surface-variant": "#444656",
                "on-secondary-fixed": "#0d1c2e",
                "tertiary-container": "#c04500",
                "surface-dim": "#d8dadc",
                "surface-container-highest": "#e0e3e5",
                "primary-container": "#3d5afe",
                "on-error-container": "#93000a",
                "background": "#f7f9fb",
                "surface-container-high": "#e6e8ea",
                "primary-fixed": "#dee0ff",
                "on-primary-fixed-variant": "#002ccd",
                "surface-container-low": "#f2f4f6",
                "on-primary-container": "#f1f0ff",
                "tertiary": "#973500",
                "inverse-on-surface": "#eff1f3",
                "surface-container": "#eceef0",
                "on-surface": "#191c1e",
                "on-secondary": "#ffffff",
                "surface-tint": "#2848ee",
                "inverse-surface": "#2d3133",
                "on-tertiary-container": "#ffeee8",
                "primary-fixed-dim": "#bbc3ff",
                "on-primary": "#ffffff",
                "on-tertiary-fixed-variant": "#7f2b00",
                "secondary-fixed-dim": "#b9c7df",
                "tertiary-fixed": "#ffdbce",
                "secondary-container": "#d5e3fc",
                "tertiary-fixed-dim": "#ffb599",
                "on-secondary-container": "#57657a",
                "on-background": "#191c1e",
                "on-error": "#ffffff"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
        },
    },
}
